name: Run unit and file system integration tests on affected packages
run-name: ${{ gitea.actor }}
on: [push]

jobs:
  Run-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RUNWORKFLOWS }}

      - name: Fetch commits
        run: |
          git fetch --deepen=1000

      - name: Detect affected packages
        run: ./infrastructure/scripts/workflows/detect-changes.sh

      - name: Show changed packages
        if: env.SKIP != 'true'
        run: |
          echo "Changed: ${{ env.CHANGED }}"

      - name: Setup Node.js
        if: env.SKIP != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        if: env.SKIP != 'true'
        run: |
          npm run setupDependencies

      - name: Run tests
        if: env.SKIP != 'true'
        run: |
          ./infrastructure/scripts/workflows/trigger-tests.sh test:unit:node-runner
        env:
          CHANGED: ${{ env.CHANGED }}

