services:
  rabbitmq:
    image: docker.io/library/rabbitmq:3-management
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 30s
      timeout: 10s
      retries: 3

  valkey:
    image: docker.io/valkey/valkey:8.1
    ports:
      - "${VALKEY_PORT}:6379"
    restart: unless-stopped

  c_p_action_requests:
    build:
      context: ../../../connector/processors/actionRequests/fromUserApiToQueue
      dockerfile: ../../../../infrastructure/containerfiles/testing/connector/processors/actionRequests/Containerfile
    depends_on:
      - rabbitmq
    volumes:
      - ../../../:/usr/src/app/
      - shared:/tmp/vc-shared
    environment:
      INTERNAL: ${INTERNAL}
      RABBITMQ_HOST: rabbitmq
      FILES_PATH_PRIVATE: /tmp
      FILES_PATH_SHARED: /tmp/vc-shared
      VALKEY_HOST: valkey

  c_p_from_tcp_interface_messages:
    build:
      context: ../../../connector/processors/fromTcpInterfaceMessages
      dockerfile: ../../../infrastructure/containerfiles/testing/connector/processors/fromTcpInterfaceMessages/Containerfile
    depends_on:
      - rabbitmq
    volumes:
      - ../../../:/usr/src/app/
      - shared:/tmp/vc-shared
    environment:
      INTERNAL: ${INTERNAL}
      RABBITMQ_HOST: rabbitmq
      FILES_PATH_PRIVATE: /tmp
      FILES_PATH_SHARED: /tmp/vc-shared
      VALKEY_HOST: valkey

  tcp_interface:
    build:
      context: ../../../connector/tcpInterface
      dockerfile: ../../infrastructure/containerfiles/testing/connector/tcpInterface/Containerfile
    ports:
      - "${TCP_PORT}:1234"
    depends_on:
      - rabbitmq
    volumes:
      - ../../../:/usr/src/app/
      - shared:/tmp/vc-shared
    environment:
      RABBITMQ_HOST: rabbitmq
      FILES_PATH_PRIVATE: /tmp
      FILES_PATH_SHARED: /tmp/vc-shared
      TCP_HOST: 0.0.0.0

  user_api:
    build:
      context: ../../../connector/userApi
      dockerfile: ../../infrastructure/containerfiles/testing/connector/userApi/Containerfile
    ports:
      - "${USER_API_PORT}:3000"
    depends_on:
      - rabbitmq
    volumes:
      - ../../../:/usr/src/app/
      - shared:/tmp/vc-shared
    environment:
      RABBITMQ_HOST: rabbitmq
      FILES_PATH_PRIVATE: /tmp
      FILES_PATH_SHARED: /tmp/vc-shared
      VALKEY_HOST: valkey
volumes:
  shared:



