#!/bin/bash

protected_branches=("main" "internal-to-public")

while read local_ref local_sha remote_ref remote_sha; do
  branch_name=$(echo "$remote_ref" | sed 's|refs/heads/||')
  if [[ " ${protected_branches[@]} " =~ " ${branch_name} " ]]; then
    echo "Direct commits not allowed for branch '$branch_name'"
    exit 1
  fi
done