name: Run unit and file system integration tests on affected packages
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  Run-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOWS_TOKEN }}

      - name: Fetch commits
        run: |
          git fetch --deepen=1000

      - name: Detect affected packages
        run: ./infrastructure/scripts/workflows/detect-changes.sh

      - name: Setup Node.js
        if: env.SKIP != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Cache node modules
        if: env.SKIP != 'true'
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup dependencies
        if: env.SKIP != 'true'
        run: npm run setupDependencies

      - name: Run tests
        if: env.SKIP != 'true'
        timeout-minutes: 10
        run: |
          set -euo pipefail
          source "infrastructure/scripts/workflows/package-deps.sh"
          echo "Changed packages: $CHANGED"
          for path in $CHANGED; do
            cd "$path"
            echo "Running tests in $path"
            if npm run | grep -q "test:unit:node-runner"; then
              npm run test:unit:node-runner;
            fi
            cd -
          done
        env:
          CHANGED: ${{ env.CHANGED }}
